server:
  port: 8080
spring:
  redis:
  dotenv:
    location: .env.local.local
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/irion?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
jwt:
  secret: ${JWT_SECRET:uvHD8V/wpgexSDSxjwQSvIKHdycC0A+XKBCfg02q/SI=}
  access-token-expiration: 3600000 # 1 hour (ms)
  refresh-token-expiration: 604800000 # 7 days (ms)
  guest-token-expiration: 3600000 # 1 hour (ms)
