server:
  port: 8080
spring:
  dotenv:
    location: .env.local
  datasource:
    url: ${DB_URL:jdbc:log4jdbc:mysql://localhost:3306/dbName} # ??? DB URL
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:5656}
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 3600000 # 1 hour (ms)
  refresh-token-expiration: 604800000 # 7 days (ms)
  guest-token-expiration: 3600000 # 1 hour (ms)
