server:
  port: 8080
spring:
  dotenv:
    location: .env
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: ${JWT_SECRET:uvHD8V/wpgexSDSxjwQSvIKHdycC0A+XKBCfg02q/SI=}
  access-token-expiration: 3600000 # 1 hour (ms)
  refresh-token-expiration: 604800000 # 7 days (ms)
  guest-token-expiration: 3600000 # 1 hour (ms)
