server:
  port: 8080
spring:
  dotenv:
    location: .env
  datasource:
    url: jdbc:mysql://localhost:3306/no_injung?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true#${DB_URL}
    username: root # ${DB_USERNAME}
    password: 1234 # ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: mySecretKey123456789mySecretKey123456789
  access-token-expiration: 3600000 # 1 hour (ms)
  refresh-token-expiration: 604800000 # 7 days (ms)
  guest-token-expiration: 3600000 # 1 hour (ms)